# ==========================================
# Order Service ? application.properties
# ==========================================
server.port=8081
spring.application.name=order-service

# --- Downstream service URLs ---
services.payment.url=http://payment-service:8082
services.inventory.url=http://inventory-service:8083

# --- SSL/mTLS (active in Scenario 3) ---
server.ssl.enabled=false
server.ssl.key-store=/certs/keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.trust-store=/certs/truststore.p12
server.ssl.trust-store-password=changeit
server.ssl.trust-store-type=PKCS12
server.ssl.client-auth=want


# --- Actuator ---
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
# Actuator on separate HTTP port ? probes use this, no mTLS needed
management.server.port=8090
management.server.ssl.enabled=false

# --- Logging ---
logging.level.com.zerotrust=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n